/* neredenyiyelim — 81 il verisi + öne çıkan mekan verisi
   Not: Mekan verileri şu an için örnek/başlangıç (taban) veridir.
   Gerçek, güncel Google verileriyle şehir şehir zenginleştirilecektir. */

const BOLGE_ADI = {
  marmara: "Marmara",
  ege: "Ege",
  akdeniz: "Akdeniz",
  icanadolu: "İç Anadolu",
  karadeniz: "Karadeniz",
  doguanadolu: "Doğu Anadolu",
  guneydogu: "Güneydoğu Anadolu",
};

const ILLER = [
  { ad: "Adana", slug: "adana", bolge: "akdeniz" },
  { ad: "Adıyaman", slug: "adiyaman", bolge: "guneydogu" },
  { ad: "Afyonkarahisar", slug: "afyonkarahisar", bolge: "ege" },
  { ad: "Ağrı", slug: "agri", bolge: "doguanadolu" },
  { ad: "Amasya", slug: "amasya", bolge: "karadeniz" },
  { ad: "Ankara", slug: "ankara", bolge: "icanadolu" },
  { ad: "Antalya", slug: "antalya", bolge: "akdeniz" },
  { ad: "Artvin", slug: "artvin", bolge: "karadeniz" },
  { ad: "Aydın", slug: "aydin", bolge: "ege" },
  { ad: "Balıkesir", slug: "balikesir", bolge: "marmara" },
  { ad: "Bilecik", slug: "bilecik", bolge: "marmara" },
  { ad: "Bingöl", slug: "bingol", bolge: "doguanadolu" },
  { ad: "Bitlis", slug: "bitlis", bolge: "doguanadolu" },
  { ad: "Bolu", slug: "bolu", bolge: "karadeniz" },
  { ad: "Burdur", slug: "burdur", bolge: "akdeniz" },
  { ad: "Bursa", slug: "bursa", bolge: "marmara" },
  { ad: "Çanakkale", slug: "canakkale", bolge: "marmara" },
  { ad: "Çankırı", slug: "cankiri", bolge: "icanadolu" },
  { ad: "Çorum", slug: "corum", bolge: "karadeniz" },
  { ad: "Denizli", slug: "denizli", bolge: "ege" },
  { ad: "Diyarbakır", slug: "diyarbakir", bolge: "guneydogu" },
  { ad: "Edirne", slug: "edirne", bolge: "marmara" },
  { ad: "Elazığ", slug: "elazig", bolge: "doguanadolu" },
  { ad: "Erzincan", slug: "erzincan", bolge: "doguanadolu" },
  { ad: "Erzurum", slug: "erzurum", bolge: "doguanadolu" },
  { ad: "Eskişehir", slug: "eskisehir", bolge: "icanadolu" },
  { ad: "Gaziantep", slug: "gaziantep", bolge: "guneydogu" },
  { ad: "Giresun", slug: "giresun", bolge: "karadeniz" },
  { ad: "Gümüşhane", slug: "gumushane", bolge: "karadeniz" },
  { ad: "Hakkari", slug: "hakkari", bolge: "doguanadolu" },
  { ad: "Hatay", slug: "hatay", bolge: "akdeniz" },
  { ad: "Isparta", slug: "isparta", bolge: "akdeniz" },
  { ad: "Mersin", slug: "mersin", bolge: "akdeniz" },
  { ad: "İstanbul", slug: "istanbul", bolge: "marmara" },
  { ad: "İzmir", slug: "izmir", bolge: "ege" },
  { ad: "Kars", slug: "kars", bolge: "doguanadolu" },
  { ad: "Kastamonu", slug: "kastamonu", bolge: "karadeniz" },
  { ad: "Kayseri", slug: "kayseri", bolge: "icanadolu" },
  { ad: "Kırklareli", slug: "kirklareli", bolge: "marmara" },
  { ad: "Kırşehir", slug: "kirsehir", bolge: "icanadolu" },
  { ad: "Kocaeli", slug: "kocaeli", bolge: "marmara" },
  { ad: "Konya", slug: "konya", bolge: "icanadolu" },
  { ad: "Kütahya", slug: "kutahya", bolge: "ege" },
  { ad: "Malatya", slug: "malatya", bolge: "doguanadolu" },
  { ad: "Manisa", slug: "manisa", bolge: "ege" },
  { ad: "Kahramanmaraş", slug: "kahramanmaras", bolge: "akdeniz" },
  { ad: "Mardin", slug: "mardin", bolge: "guneydogu" },
  { ad: "Muğla", slug: "mugla", bolge: "ege" },
  { ad: "Muş", slug: "mus", bolge: "doguanadolu" },
  { ad: "Nevşehir", slug: "nevsehir", bolge: "icanadolu" },
  { ad: "Niğde", slug: "nigde", bolge: "icanadolu" },
  { ad: "Ordu", slug: "ordu", bolge: "karadeniz" },
  { ad: "Rize", slug: "rize", bolge: "karadeniz" },
  { ad: "Sakarya", slug: "sakarya", bolge: "marmara" },
  { ad: "Samsun", slug: "samsun", bolge: "karadeniz" },
  { ad: "Siirt", slug: "siirt", bolge: "guneydogu" },
  { ad: "Sinop", slug: "sinop", bolge: "karadeniz" },
  { ad: "Sivas", slug: "sivas", bolge: "icanadolu" },
  { ad: "Tekirdağ", slug: "tekirdag", bolge: "marmara" },
  { ad: "Tokat", slug: "tokat", bolge: "karadeniz" },
  { ad: "Trabzon", slug: "trabzon", bolge: "karadeniz" },
  { ad: "Tunceli", slug: "tunceli", bolge: "doguanadolu" },
  { ad: "Şanlıurfa", slug: "sanliurfa", bolge: "guneydogu" },
  { ad: "Uşak", slug: "usak", bolge: "ege" },
  { ad: "Van", slug: "van", bolge: "doguanadolu" },
  { ad: "Yozgat", slug: "yozgat", bolge: "icanadolu" },
  { ad: "Zonguldak", slug: "zonguldak", bolge: "karadeniz" },
  { ad: "Aksaray", slug: "aksaray", bolge: "icanadolu" },
  { ad: "Bayburt", slug: "bayburt", bolge: "karadeniz" },
  { ad: "Karaman", slug: "karaman", bolge: "icanadolu" },
  { ad: "Kırıkkale", slug: "kirikkale", bolge: "icanadolu" },
  { ad: "Batman", slug: "batman", bolge: "guneydogu" },
  { ad: "Şırnak", slug: "sirnak", bolge: "guneydogu" },
  { ad: "Bartın", slug: "bartin", bolge: "karadeniz" },
  { ad: "Ardahan", slug: "ardahan", bolge: "doguanadolu" },
  { ad: "Iğdır", slug: "igdir", bolge: "doguanadolu" },
  { ad: "Yalova", slug: "yalova", bolge: "marmara" },
  { ad: "Karabük", slug: "karabuk", bolge: "karadeniz" },
  { ad: "Kilis", slug: "kilis", bolge: "guneydogu" },
  { ad: "Osmaniye", slug: "osmaniye", bolge: "akdeniz" },
  { ad: "Düzce", slug: "duzce", bolge: "karadeniz" },
];

function img(id, w) {
  return `https://images.pexels.com/photos/${id}/pexels-photo-${id}.jpeg?auto=compress&cs=tinysrgb&w=${w || 900}`;
}

const GORSEL = {
  meyhane: 1279330, kahve: 302896, osmanli: 1516415, sokak: 262978, tatli: 291528,
  et: 106343, geleneksel: 1516415, zeytinyagli: 1435904, pide: 1146760, kahvalti: 376464,
  deniz: 725991, meze: 725991, ege: 1435904, boza: 302896, sahil: 1058277,
};

const MEKANLAR = [
  // ---------------- İSTANBUL ----------------
  {
    id: "istanbul-1", il: "istanbul", ad: "Boğaz Kıyısı Meyhane", kategori: "Meyhane & Balık",
    puan: 4.8, yorumSayisi: 9840, fiyat: "₺₺₺", trend: true,
    adres: "Ortaköy Sahili, Beşiktaş / İstanbul",
    gorsel: img(GORSEL.meyhane), galeri: [img(GORSEL.meyhane), img(GORSEL.deniz), img(GORSEL.meze)],
    ozellikler: ["Boğaz Manzarası", "Canlı Müzik", "Rezervasyon Şart"],
    alinti: "\"Meze çeşitliliği ve servis kalitesi bu seviyede az bulunur.\"",
    neden: "Boğaz'a sıfır konumu ve mevsimlik meze menüsüyle İstanbul'un en çok yorum alan meyhanelerinden — özellikle gün batımı saatlerinde masa bulmak zor.",
    menu: [
      { ad: "Soğuk Meze Tabağı", fiyat: "₺320" },
      { ad: "Levrek Buğulama", fiyat: "₺680" },
      { ad: "Ahtapot Izgara", fiyat: "₺750" },
      { ad: "Rakı (Tekli)", fiyat: "₺180" },
    ],
    yorumlar: [
      { ad: "Elif K.", puan: 5, yorum: "Manzara ve lezzet bir arada, özel günler için ideal." },
      { ad: "Mert Y.", puan: 5, yorum: "Balık taze, servis hızlı. Kesinlikle rezervasyon yapın." },
    ],
  },
  {
    id: "istanbul-2", il: "istanbul", ad: "Karaköy Kahve Atölyesi", kategori: "Kahve & Kahvaltı",
    puan: 4.7, yorumSayisi: 6210, fiyat: "₺₺",
    adres: "Kemankeş Cd., Karaköy, Beyoğlu / İstanbul",
    gorsel: img(GORSEL.kahve), galeri: [img(GORSEL.kahve), img(GORSEL.kahvalti), img(GORSEL.tatli)],
    ozellikler: ["Üçüncü Nesil Kahve", "Sessiz Çalışma Alanı", "Evcil Hayvan Dostu"],
    alinti: "\"Filtre kahve seçenekleri ve sakin atmosferiyle sabah rutinim oldu.\"",
    neden: "Kendi kavurduğu çekirdeklerle hazırlanan filtre kahve menüsü ve minimal iç mekanıyla dijital göçebelerin uğrak noktası.",
    menu: [
      { ad: "V60 Filtre Kahve", fiyat: "₺140" },
      { ad: "Flat White", fiyat: "₺150" },
      { ad: "Avokadolu Tost", fiyat: "₺220" },
      { ad: "Ev Yapımı Cheesecake", fiyat: "₺190" },
    ],
    yorumlar: [
      { ad: "Deniz A.", puan: 5, yorum: "Kahveleri gerçekten farklı bir seviyede." },
      { ad: "Zeynep T.", puan: 4, yorum: "Biraz kalabalık olabiliyor ama lezzet buna değer." },
    ],
  },
  {
    id: "istanbul-3", il: "istanbul", ad: "Sultanahmet Osmanlı Sofrası", kategori: "Osmanlı Mutfağı",
    puan: 4.6, yorumSayisi: 15200,
    fiyat: "₺₺₺", adres: "Sultanahmet Meydanı Yakını, Fatih / İstanbul",
    gorsel: img(GORSEL.osmanli), galeri: [img(GORSEL.osmanli), img(GORSEL.et), img(GORSEL.geleneksel)],
    ozellikler: ["Tarihi Mekan", "Turist Dostu Menü", "Terasta Oturma"],
    alinti: "\"Otantik Osmanlı tatlarını modern sunumla birleştirmişler.\"",
    neden: "Tarihi yarımadanın kalbinde, has ahşap dekoru ve saray mutfağından esinlenen tabaklarıyla yerli-yabancı herkesin listesinde.",
    menu: [
      { ad: "Hünkar Beğendi", fiyat: "₺420" },
      { ad: "Kuzu Tandır", fiyat: "₺580" },
      { ad: "Osmanlı Macunu", fiyat: "₺160" },
      { ad: "Şerbetli Tatlı Tabağı", fiyat: "₺210" },
    ],
    yorumlar: [
      { ad: "James R.", puan: 5, yorum: "Best Ottoman cuisine experience in the old city." },
      { ad: "Ayşe B.", puan: 4, yorum: "Fiyatlar turistik bölgeye göre normal, lezzet iyi." },
    ],
  },
  {
    id: "istanbul-4", il: "istanbul", ad: "Kadıköy Sokak Lezzetleri", kategori: "Sokak Lezzeti",
    puan: 4.5, yorumSayisi: 4830,
    fiyat: "₺", adres: "Moda Cd., Kadıköy / İstanbul",
    gorsel: img(GORSEL.sokak), galeri: [img(GORSEL.sokak), img(GORSEL.pide), img(GORSEL.et)],
    ozellikler: ["Uygun Fiyat", "Hızlı Servis", "Gece Geç Saate Açık"],
    alinti: "\"Kadıköy'de gece yarısı en iyi çiğköfte burada.\"",
    neden: "Semtin gece hayatının merkezinde, öğrenci bütçesine uygun ama kaliteden ödün vermeyen sokak lezzetleri sunuyor.",
    menu: [
      { ad: "Çiğköfte Dürüm", fiyat: "₺95" },
      { ad: "Kokoreç Yarım Ekmek", fiyat: "₺130" },
      { ad: "Islak Hamburger", fiyat: "₺80" },
      { ad: "Ayran", fiyat: "₺35" },
    ],
    yorumlar: [
      { ad: "Barış K.", puan: 5, yorum: "Fiyat performans açısından Kadıköy'de zirvede." },
      { ad: "Selin Ö.", puan: 4, yorum: "Kuyruk oluyor ama hızlı ilerliyor." },
    ],
  },
  {
    id: "istanbul-5", il: "istanbul", ad: "Beyoğlu Tatlı Han", kategori: "Tatlı & Pastane",
    puan: 4.9, yorumSayisi: 7360, trend: true,
    fiyat: "₺₺", adres: "İstiklal Cd. Yakını, Beyoğlu / İstanbul",
    gorsel: img(GORSEL.tatli), galeri: [img(GORSEL.tatli), img(GORSEL.kahve), img(GORSEL.osmanli)],
    ozellikler: ["Günlük Taze Üretim", "Vitrin Şovu", "Instagram'lık Sunum"],
    alinti: "\"Künefe ve profiterolü aynı anda söylediğime pişman olmadım.\"",
    neden: "Günlük taze üretim ilkesiyle çalışan, hem klasik hem füzyon tatlıları aynı vitrinde buluşturan semtin en çok fotoğraflanan durağı.",
    menu: [
      { ad: "Fıstıklı Künefe", fiyat: "₺260" },
      { ad: "Profiterol", fiyat: "₺210" },
      { ad: "San Sebastian Cheesecake", fiyat: "₺240" },
      { ad: "Türk Kahvesi", fiyat: "₺110" },
    ],
    yorumlar: [
      { ad: "Nil D.", puan: 5, yorum: "Şehrin en iyi tatlıcılarından biri, tereddütsüz." },
      { ad: "Kerem S.", puan: 5, yorum: "Sunum ve lezzet birebir örtüşüyor." },
    ],
  },

  // ---------------- ANKARA ----------------
  {
    id: "ankara-1", il: "ankara", ad: "Kızılay Et Lokantası", kategori: "Et & Izgara",
    puan: 4.7, yorumSayisi: 8120, trend: true,
    fiyat: "₺₺₺", adres: "Kızılay Meydanı Yakını, Çankaya / Ankara",
    gorsel: img(GORSEL.et), galeri: [img(GORSEL.et), img(GORSEL.geleneksel), img(GORSEL.osmanli)],
    ozellikler: ["Odun Ateşinde Pişirim", "Aile Dostu", "Geniş Otopark"],
    alinti: "\"Ankara'da bu kalitede kuzu pirzola bulmak kolay değil.\"",
    neden: "Kasaplığından gelen et kalitesi ve odun ateşinde pişirim tekniğiyle şehrin klasikleşmiş et lokantalarından.",
    menu: [
      { ad: "Kuzu Pirzola", fiyat: "₺620" },
      { ad: "Adana Kebap", fiyat: "₺380" },
      { ad: "Ali Nazik", fiyat: "₺340" },
      { ad: "Künefe", fiyat: "₺220" },
    ],
    yorumlar: [
      { ad: "Onur B.", puan: 5, yorum: "Et kalitesi ve pişirim mükemmel." },
      { ad: "Gizem A.", puan: 4, yorum: "Hafta sonu rezervasyonsuz zor, ama değer." },
    ],
  },
  {
    id: "ankara-2", il: "ankara", ad: "Hamamönü Osmanlı Evi", kategori: "Geleneksel Türk Mutfağı",
    puan: 4.6, yorumSayisi: 5340,
    fiyat: "₺₺", adres: "Hamamönü, Altındağ / Ankara",
    gorsel: img(GORSEL.geleneksel), galeri: [img(GORSEL.geleneksel), img(GORSEL.osmanli), img(GORSEL.kahvalti)],
    ozellikler: ["Tarihi Konak", "Avlu Bahçesi", "El Yapımı Hamur İşleri"],
    alinti: "\"Restore edilmiş konakta yemek yemek ayrı bir keyif.\"",
    neden: "Restore edilmiş bir Ankara konağında, ev yapımı mantı ve gözlemeden oluşan otantik bir menü sunuyor.",
    menu: [
      { ad: "El Açması Mantı", fiyat: "₺260" },
      { ad: "Etli Ekmek", fiyat: "₺230" },
      { ad: "Höşmerim", fiyat: "₺170" },
      { ad: "Ayran", fiyat: "₺40" },
    ],
    yorumlar: [
      { ad: "Ceren F.", puan: 5, yorum: "Avluda oturmak, mantısı kadar güzel." },
      { ad: "Tolga E.", puan: 4, yorum: "Lezzet gayet iyi, servis biraz yavaş." },
    ],
  },
  {
    id: "ankara-3", il: "ankara", ad: "Çankaya Zeytinyağlılar", kategori: "Zeytinyağlı & Ege Mutfağı",
    puan: 4.5, yorumSayisi: 3120,
    fiyat: "₺₺", adres: "Çankaya, Ankara",
    gorsel: img(GORSEL.zeytinyagli), galeri: [img(GORSEL.zeytinyagli), img(GORSEL.ege), img(GORSEL.meze)],
    ozellikler: ["Vejetaryen Dostu", "Günlük Değişen Menü", "Ev Yemeği Tadında"],
    alinti: "\"Vejetaryen olmasam da her hafta buraya geliyorum.\"",
    neden: "Günlük değişen zeytinyağlı menüsüyle hem vejetaryenlerin hem de hafif beslenmek isteyenlerin favorisi.",
    menu: [
      { ad: "Günün Zeytinyağlısı", fiyat: "₺140" },
      { ad: "Yaprak Sarma", fiyat: "₺160" },
      { ad: "Enginar Dolması", fiyat: "₺190" },
      { ad: "Ev Yapımı Limonata", fiyat: "₺70" },
    ],
    yorumlar: [
      { ad: "Pınar C.", puan: 5, yorum: "Hem sağlıklı hem lezzetli, nadir bir kombinasyon." },
      { ad: "Emre G.", puan: 4, yorum: "Porsiyonlar biraz küçük ama tadı çok iyi." },
    ],
  },
  {
    id: "ankara-4", il: "ankara", ad: "Bahçelievler Pide Sofrası", kategori: "Pide & Lahmacun",
    puan: 4.4, yorumSayisi: 6710,
    fiyat: "₺", adres: "Bahçelievler, Çankaya / Ankara",
    gorsel: img(GORSEL.pide), galeri: [img(GORSEL.pide), img(GORSEL.et), img(GORSEL.sokak)],
    ozellikler: ["Taş Fırın", "Aile Sofrası", "Hızlı Servis"],
    alinti: "\"Kaşarlı pidesi şehrin en iyilerinden.\"",
    neden: "Taş fırında pişen ince hamuruyla, üniversite yıllarından beri Ankaralıların vazgeçemediği bir mahalle klasiği.",
    menu: [
      { ad: "Kaşarlı Pide", fiyat: "₺190" },
      { ad: "Kıymalı Pide", fiyat: "₺210" },
      { ad: "Lahmacun (Adet)", fiyat: "₺60" },
      { ad: "Künefe", fiyat: "₺180" },
    ],
    yorumlar: [
      { ad: "Buse Y.", puan: 5, yorum: "Hamur işi konusunda iddialılar ve haklılar." },
      { ad: "Kaan T.", puan: 4, yorum: "Fiyat performans açısından çok iyi." },
    ],
  },
  {
    id: "ankara-5", il: "ankara", ad: "Ankara Kahvaltı Durağı", kategori: "Kahvaltı",
    puan: 4.8, yorumSayisi: 5980, trend: true,
    fiyat: "₺₺", adres: "Bahçelievler, Ankara",
    gorsel: img(GORSEL.kahvalti), galeri: [img(GORSEL.kahvalti), img(GORSEL.tatli), img(GORSEL.kahve)],
    ozellikler: ["Serpme Kahvaltı", "Bahçe Alanı", "Organik Ürünler"],
    alinti: "\"Serpme kahvaltı tabağı iki kişiye zor yetiyor, o kadar dolu.\"",
    neden: "Yöresel reçeller ve köy peynirleriyle hazırlanan serpme kahvaltısıyla hafta sonu kahvaltı kültürünün merkezlerinden.",
    menu: [
      { ad: "Serpme Kahvaltı (Kişi Başı)", fiyat: "₺380" },
      { ad: "Sahanda Sucuklu Yumurta", fiyat: "₺210" },
      { ad: "Ev Yapımı Reçel Tabağı", fiyat: "₺120" },
      { ad: "Çay (Semaver)", fiyat: "₺90" },
    ],
    yorumlar: [
      { ad: "Aslı M.", puan: 5, yorum: "Reçelleri ev yapımı ve gerçekten çok lezzetli." },
      { ad: "Fatih K.", puan: 5, yorum: "Bahçede kahvaltı keyfi başka bir şey." },
    ],
  },

  // ---------------- İZMİR ----------------
  {
    id: "izmir-1", il: "izmir", ad: "Kordon Balık Evi", kategori: "Deniz Ürünleri",
    puan: 4.7, yorumSayisi: 7430, trend: true,
    fiyat: "₺₺₺", adres: "Kordon Boyu, Alsancak / İzmir",
    gorsel: img(GORSEL.deniz), galeri: [img(GORSEL.deniz), img(GORSEL.meze), img(GORSEL.sahil)],
    ozellikler: ["Deniz Manzarası", "Günlük Balık", "Gün Batımı Terası"],
    alinti: "\"Gün batımında kordon boyunda taze balık, İzmir'in özeti gibi.\"",
    neden: "Her sabah balıkçı halinden temin edilen günlük av ile hazırlanan menüsü ve kordon manzarasıyla şehrin klasik adreslerinden.",
    menu: [
      { ad: "Çupra Izgara", fiyat: "₺520" },
      { ad: "Karides Güveç", fiyat: "₺480" },
      { ad: "Deniz Mahsulleri Meze Tabağı", fiyat: "₺340" },
      { ad: "Beyaz Şarap (Kadeh)", fiyat: "₺160" },
    ],
    yorumlar: [
      { ad: "Yasemin Ö.", puan: 5, yorum: "Balık taptaze, manzara muhteşem." },
      { ad: "Cem A.", puan: 4, yorum: "Fiyatlar biraz yüksek ama kalite hak ediyor." },
    ],
  },
  {
    id: "izmir-2", il: "izmir", ad: "Alsancak Meze Sofrası", kategori: "Meze & Rakı Sofrası",
    puan: 4.6, yorumSayisi: 4210,
    fiyat: "₺₺₺", adres: "Alsancak, Konak / İzmir",
    gorsel: img(GORSEL.meze), galeri: [img(GORSEL.meze), img(GORSEL.deniz), img(GORSEL.ege)],
    ozellikler: ["Canlı Fasıl", "Geniş Meze Menüsü", "Gece Geç Saate Açık"],
    alinti: "\"İzmir'in fasıl kültürünü en iyi yaşadığım yer.\"",
    neden: "Yetmişi aşkın meze çeşidi ve hafta sonları canlı fasıl programıyla İzmir gece hayatının vazgeçilmezi.",
    menu: [
      { ad: "Meze Çeşitleri (6'lı)", fiyat: "₺380" },
      { ad: "Midye Dolma (10 Adet)", fiyat: "₺220" },
      { ad: "Kalamar Tava", fiyat: "₺360" },
      { ad: "Rakı (Tekli)", fiyat: "₺180" },
    ],
    yorumlar: [
      { ad: "Derya S.", puan: 5, yorum: "Meze çeşitliliği inanılmaz, hepsi lezzetli." },
      { ad: "Volkan Ç.", puan: 4, yorum: "Fasıl geceleri çok keyifli, erken rezervasyon şart." },
    ],
  },
  {
    id: "izmir-3", il: "izmir", ad: "Karşıyaka Zeytinyağlı Mutfak", kategori: "Ege Zeytinyağlıları",
    puan: 4.5, yorumSayisi: 2870,
    fiyat: "₺₺", adres: "Karşıyaka, İzmir",
    gorsel: img(GORSEL.ege), galeri: [img(GORSEL.ege), img(GORSEL.zeytinyagli), img(GORSEL.meze)],
    ozellikler: ["Mevsim Otları", "Vejetaryen Dostu", "Ev Yapımı Ekmek"],
    alinti: "\"Ege otlarıyla hazırlanan yemekler adeta bir sanat eseri.\"",
    neden: "Yöre kadınlarından öğrenilen tariflerle, mevsimlik Ege otlarını zeytinyağıyla buluşturan otantik bir mutfak.",
    menu: [
      { ad: "Ot Tabağı (Karışık)", fiyat: "₺180" },
      { ad: "Enginarlı Bakla", fiyat: "₺200" },
      { ad: "Zeytinyağlı Barbunya", fiyat: "₺150" },
      { ad: "Ev Yapımı Ekmek", fiyat: "₺40" },
    ],
    yorumlar: [
      { ad: "Sibel N.", puan: 5, yorum: "Ege mutfağının en saf haliyle karşılaşıyorsunuz." },
      { ad: "Uğur D.", puan: 4, yorum: "Sade ama çok lezzetli, tavsiye ederim." },
    ],
  },
  {
    id: "izmir-4", il: "izmir", ad: "Kemeraltı Boza & Kahve", kategori: "Geleneksel İçecek",
    puan: 4.4, yorumSayisi: 1950,
    fiyat: "₺", adres: "Kemeraltı Çarşısı, Konak / İzmir",
    gorsel: img(GORSEL.boza), galeri: [img(GORSEL.boza), img(GORSEL.kahve), img(GORSEL.sokak)],
    ozellikler: ["Tarihi Çarşı İçinde", "Yerel Lezzet", "Uygun Fiyat"],
    alinti: "\"Kemeraltı'nda gezerken uğranacak en samimi durak.\"",
    neden: "Yüz yılı aşkın süredir aynı reçeteyle boza yapan, çarşı esnafının da uğrak noktası olan küçük ama efsanevi bir dükkan.",
    menu: [
      { ad: "Boza (Tarçınlı)", fiyat: "₺60" },
      { ad: "Türk Kahvesi", fiyat: "₺70" },
      { ad: "Leblebi Tabağı", fiyat: "₺40" },
      { ad: "Şeker Katkısız Boza", fiyat: "₺65" },
    ],
    yorumlar: [
      { ad: "Hakan İ.", puan: 5, yorum: "Otantik lezzet, geleneği yaşatıyorlar." },
      { ad: "Melis R.", puan: 4, yorum: "Küçük bir yer ama atmosferi çok güzel." },
    ],
  },
  {
    id: "izmir-5", il: "izmir", ad: "Foça Sahil Restoran", kategori: "Deniz Ürünleri & Manzara",
    puan: 4.8, yorumSayisi: 3640, trend: true,
    fiyat: "₺₺₺", adres: "Foça Sahili, İzmir",
    gorsel: img(GORSEL.sahil), galeri: [img(GORSEL.sahil), img(GORSEL.deniz), img(GORSEL.ege)],
    ozellikler: ["Deniz Kenarı Masa", "Gün Batımı Manzarası", "Taze Balık"],
    alinti: "\"Ayaklarınız neredeyse suya değecek, o kadar sahile yakın.\"",
    neden: "Foça'nın sakin koyuna nazır terasıyla, hafta sonu kaçamakları için İzmirlilerin ilk tercihi.",
    menu: [
      { ad: "Levrek Buğulama", fiyat: "₺560" },
      { ad: "Karides Güveç", fiyat: "₺490" },
      { ad: "Deniz Börülcesi Salata", fiyat: "₺150" },
      { ad: "Taze Sıkılmış Limonata", fiyat: "₺80" },
    ],
    yorumlar: [
      { ad: "Ebru L.", puan: 5, yorum: "Manzara ve lezzet mükemmel bir uyum içinde." },
      { ad: "Serkan P.", puan: 5, yorum: "Gün batımında burada olmak ayrı bir keyif." },
    ],
  },

  // ---------------- BURSA ----------------
  {
    id: "bursa-1", il: "bursa", ad: "Ulu Cami Yanı İskender", kategori: "İskender Kebap",
    puan: 4.9, yorumSayisi: 11200, trend: true,
    fiyat: "₺₺", adres: "Ulu Cami Civarı, Osmangazi / Bursa",
    gorsel: img(GORSEL.et), galeri: [img(GORSEL.et), img(GORSEL.osmanli), img(GORSEL.geleneksel)],
    ozellikler: ["Orijinal Reçete", "Tereyağında Kavrulmuş", "Aile İşletmesi"],
    alinti: "\"Bursa'ya gelip burada İskender yemeden dönmek olmaz.\"",
    neden: "Dört nesildir aynı aile tarafından işletilen, İskender kebabın doğduğu şehirdeki en özgün adreslerden.",
    menu: [
      { ad: "İskender Kebap (Tek Porsiyon)", fiyat: "₺340" },
      { ad: "İskender Kebap (Büyük Porsiyon)", fiyat: "₺460" },
      { ad: "Ayran", fiyat: "₺40" },
      { ad: "Kemalpaşa Tatlısı", fiyat: "₺140" },
    ],
    yorumlar: [
      { ad: "Aylin V.", puan: 5, yorum: "Yediğim en iyi İskender, tartışmasız." },
      { ad: "Burak H.", puan: 5, yorum: "Tereyağ kokusu ve et kalitesi bambaşka." },
    ],
  },
  {
    id: "bursa-2", il: "bursa", ad: "Cumalıkızık Köy Sofrası", kategori: "Köy Mutfağı",
    puan: 4.6, yorumSayisi: 3980,
    fiyat: "₺₺", adres: "Cumalıkızık Köyü, Yıldırım / Bursa",
    gorsel: img(GORSEL.geleneksel), galeri: [img(GORSEL.geleneksel), img(GORSEL.kahvalti), img(GORSEL.zeytinyagli)],
    ozellikler: ["Tarihi Köy Evi", "Odun Sobasında Pişirim", "Manzaralı Bahçe"],
    alinti: "\"Osmanlı köyünde zamanda yolculuk yapmış gibi hissettim.\"",
    neden: "UNESCO listesindeki tarihi köyün taş evlerinde, odun sobasında pişen gözleme ve köy kahvaltısıyla ünlü.",
    menu: [
      { ad: "Köy Kahvaltısı (Kişi Başı)", fiyat: "₺320" },
      { ad: "Sac Gözleme", fiyat: "₺130" },
      { ad: "Ev Yapımı Tarhana Çorbası", fiyat: "₺110" },
      { ad: "Kemalpaşa Tatlısı", fiyat: "₺140" },
    ],
    yorumlar: [
      { ad: "Nazan İ.", puan: 5, yorum: "Hem tarih hem lezzet bir arada." },
      { ad: "Ozan F.", puan: 4, yorum: "Hafta sonu çok kalabalık oluyor, erken gidin." },
    ],
  },
  {
    id: "bursa-3", il: "bursa", ad: "Kestane Şekeri Atölyesi", kategori: "Tatlı",
    puan: 4.7, yorumSayisi: 2650,
    fiyat: "₺₺", adres: "Osmangazi, Bursa",
    gorsel: img(GORSEL.tatli), galeri: [img(GORSEL.tatli), img(GORSEL.kahve), img(GORSEL.osmanli)],
    ozellikler: ["El Yapımı Üretim", "Yöresel Reçete", "Hediyelik Kutu Seçenekleri"],
    alinti: "\"Bursa'nın meşhur kestane şekerini en taze haliyle burada bulabilirsiniz.\"",
    neden: "Geleneksel yöntemlerle el yapımı üretim yapan, Bursa'nın şehir dışına en çok hediye edilen lezzetinin adresi.",
    menu: [
      { ad: "Kestane Şekeri (250 gr)", fiyat: "₺260" },
      { ad: "Kestane Kremalı Pasta Dilimi", fiyat: "₺160" },
      { ad: "Türk Kahvesi", fiyat: "₺100" },
      { ad: "Hediyelik Kutu (500 gr)", fiyat: "₺480" },
    ],
    yorumlar: [
      { ad: "Gül T.", puan: 5, yorum: "Kıvamı ve tazeliği harika, hediyelik olarak da mükemmel." },
      { ad: "Rıdvan Ş.", puan: 4, yorum: "Biraz pahalı ama kalite hissediliyor." },
    ],
  },
  {
    id: "bursa-4", il: "bursa", ad: "Uludağ Manzaralı Kahvaltı Evi", kategori: "Kahvaltı & Manzara",
    puan: 4.8, yorumSayisi: 4120, trend: true,
    fiyat: "₺₺", adres: "Uludağ Eteği, Bursa",
    gorsel: img(GORSEL.kahvalti), galeri: [img(GORSEL.kahvalti), img(GORSEL.tatli), img(GORSEL.geleneksel)],
    ozellikler: ["Dağ Manzarası", "Organik Süt Ürünleri", "Şömineli Salon"],
    alinti: "\"Kış aylarında şöminenin yanında kahvaltı ayrı bir keyif.\"",
    neden: "Uludağ'ın eteklerinde, kendi çiftliğinden gelen süt ürünleriyle hazırlanan zengin kahvaltı tabağıyla tanınıyor.",
    menu: [
      { ad: "Dağ Evi Kahvaltısı (Kişi Başı)", fiyat: "₺360" },
      { ad: "Tereyağlı Bal Tabağı", fiyat: "₺150" },
      { ad: "Sıcak Sahanda Yumurta", fiyat: "₺190" },
      { ad: "Sahlep", fiyat: "₺110" },
    ],
    yorumlar: [
      { ad: "İpek O.", puan: 5, yorum: "Manzara ve peynir çeşitleri unutulmaz." },
      { ad: "Metin U.", puan: 5, yorum: "Kış sabahları için birebir." },
    ],
  },
  {
    id: "bursa-5", il: "bursa", ad: "Mudanya Balık Lokantası", kategori: "Deniz Ürünleri",
    puan: 4.5, yorumSayisi: 2340,
    fiyat: "₺₺₺", adres: "Mudanya Sahili, Bursa",
    gorsel: img(GORSEL.deniz), galeri: [img(GORSEL.deniz), img(GORSEL.sahil), img(GORSEL.meze)],
    ozellikler: ["Marmara Manzarası", "Günlük Balık", "Aile İşletmesi"],
    alinti: "\"Mudanya'da sahilde balık yemenin en keyifli hali.\"",
    neden: "Marmara Denizi'ne nazır terasında, günlük getirilen balıklarla hazırlanan sade ama lezzetli menüsüyle öne çıkıyor.",
    menu: [
      { ad: "Çipura Izgara", fiyat: "₺480" },
      { ad: "Kalamar Tava", fiyat: "₺340" },
      { ad: "Deniz Mahsulleri Salatası", fiyat: "₺220" },
      { ad: "Beyaz Şarap (Kadeh)", fiyat: "₺150" },
    ],
    yorumlar: [
      { ad: "Selen A.", puan: 5, yorum: "Sahilde gün batımıyla balık, tam bir keyif." },
      { ad: "Yusuf B.", puan: 4, yorum: "Servis içten, lezzet gayet iyi." },
    ],
  },

  // ---------------- ANTALYA ----------------
  {
    id: "antalya-1", il: "antalya", ad: "Kaleiçi Deniz Manzaralı Restoran", kategori: "Deniz Ürünleri & Manzara",
    puan: 4.8, yorumSayisi: 9870, trend: true,
    fiyat: "₺₺₺", adres: "Kaleiçi, Muratpaşa / Antalya",
    gorsel: img(GORSEL.sahil), galeri: [img(GORSEL.sahil), img(GORSEL.deniz), img(GORSEL.meze)],
    ozellikler: ["Tarihi Liman Manzarası", "Taze Deniz Ürünleri", "Romantik Atmosfer"],
    alinti: "\"Kaleiçi'nin taş sokaklarından limana açılan en güzel teras.\"",
    neden: "Antik liman manzarasına nazır terasıyla, hem yerli hem yabancı turistlerin en çok yorum bıraktığı adreslerden.",
    menu: [
      { ad: "Levrek Buğulama", fiyat: "₺620" },
      { ad: "Karides Güveç", fiyat: "₺540" },
      { ad: "Akdeniz Meze Tabağı", fiyat: "₺320" },
      { ad: "Beyaz Şarap (Kadeh)", fiyat: "₺170" },
    ],
    yorumlar: [
      { ad: "Sophie M.", puan: 5, yorum: "Stunning harbor view, unforgettable dinner." },
      { ad: "Emirhan Ç.", puan: 5, yorum: "Manzara ve lezzet birlikte zirvede." },
    ],
  },
  {
    id: "antalya-2", il: "antalya", ad: "Lara Sahil Steakhouse", kategori: "Et & Steak",
    puan: 4.6, yorumSayisi: 5230,
    fiyat: "₺₺₺", adres: "Lara Sahili, Muratpaşa / Antalya",
    gorsel: img(GORSEL.et), galeri: [img(GORSEL.et), img(GORSEL.sahil), img(GORSEL.geleneksel)],
    ozellikler: ["Kum Sahile Sıfır", "Özel Marine Soslar", "Gün Batımı Manzarası"],
    alinti: "\"Sahilde ayaklarınız kumda, önünüzde mükemmel bir steak.\"",
    neden: "Lara sahiline sıfır konumu ve özel marine tekniğiyle pişirdiği etleriyle akşam yemeği için popüler bir seçim.",
    menu: [
      { ad: "Antrikot Steak (250 gr)", fiyat: "₺680" },
      { ad: "Tavuk Şiş", fiyat: "₺320" },
      { ad: "Izgara Sebze Tabağı", fiyat: "₺180" },
      { ad: "Cheesecake", fiyat: "₺200" },
    ],
    yorumlar: [
      { ad: "Alperen Y.", puan: 5, yorum: "Etin pişme derecesi tam istediğim gibiydi." },
      { ad: "Laura K.", puan: 4, yorum: "Great sunset view with dinner." },
    ],
  },
  {
    id: "antalya-3", il: "antalya", ad: "Kepez Testi Kebap Evi", kategori: "Geleneksel & Testi Kebap",
    puan: 4.7, yorumSayisi: 3410,
    fiyat: "₺₺", adres: "Kepez, Antalya",
    gorsel: img(GORSEL.geleneksel), galeri: [img(GORSEL.geleneksel), img(GORSEL.et), img(GORSEL.osmanli)],
    ozellikler: ["Toprak Testide Pişirim", "Masada Kırılan Testi Şovu", "Aile Dostu"],
    alinti: "\"Testinin masada kırılma anı yemeğe ayrı bir keyif katıyor.\"",
    neden: "Toprak testide saatlerce pişirilen kebabıyla, hem lezzet hem de görsel bir deneyim sunan yöresel bir mekan.",
    menu: [
      { ad: "Testi Kebap (Kuzu)", fiyat: "₺420" },
      { ad: "Testi Kebap (Tavuk)", fiyat: "₺340" },
      { ad: "Piyaz", fiyat: "₺110" },
      { ad: "Ayran", fiyat: "₺40" },
    ],
    yorumlar: [
      { ad: "Berkay N.", puan: 5, yorum: "Şov kısmı çocuklarımın da çok hoşuna gitti." },
      { ad: "Hande Z.", puan: 4, yorum: "Lezzetli ama biraz zaman alıyor pişirmesi." },
    ],
  },
  {
    id: "antalya-4", il: "antalya", ad: "Konyaaltı Kahvaltı Bahçesi", kategori: "Kahvaltı & Bahçe",
    puan: 4.5, yorumSayisi: 4670,
    fiyat: "₺₺", adres: "Konyaaltı, Antalya",
    gorsel: img(GORSEL.kahvalti), galeri: [img(GORSEL.kahvalti), img(GORSEL.tatli), img(GORSEL.sahil)],
    ozellikler: ["Deniz Manzaralı Bahçe", "Serpme Kahvaltı", "Gölgelik Alan"],
    alinti: "\"Palmiyelerin altında, deniz manzarasıyla kahvaltı keyfi.\"",
    neden: "Konyaaltı sahiline yürüme mesafesinde, tropik bahçesinde sunulan zengin serpme kahvaltısıyla tercih ediliyor.",
    menu: [
      { ad: "Serpme Kahvaltı (Kişi Başı)", fiyat: "₺350" },
      { ad: "Menemen", fiyat: "₺180" },
      { ad: "Taze Sıkılmış Portakal Suyu", fiyat: "₺90" },
      { ad: "Bal Kaymak", fiyat: "₺160" },
    ],
    yorumlar: [
      { ad: "Ceyda P.", puan: 5, yorum: "Bahçesi gerçekten çok huzurlu." },
      { ad: "Timur A.", puan: 4, yorum: "Yoğun saatlerde bekleme olabiliyor." },
    ],
  },
  {
    id: "antalya-5", il: "antalya", ad: "Side Antik Sofra", kategori: "Akdeniz Mutfağı",
    puan: 4.6, yorumSayisi: 2980,
    fiyat: "₺₺₺", adres: "Side Antik Kenti Yakını, Antalya",
    gorsel: img(GORSEL.ege), galeri: [img(GORSEL.ege), img(GORSEL.deniz), img(GORSEL.meze)],
    ozellikler: ["Antik Kalıntı Manzarası", "Akşam Işıklandırması", "Şarap Menüsü"],
    alinti: "\"Antik sütunların gölgesinde akşam yemeği, unutulmaz bir deneyim.\"",
    neden: "Side'nin antik kalıntılarına nazır konumuyla, akşamları özel ışıklandırmasıyla romantik bir atmosfer sunuyor.",
    menu: [
      { ad: "Zeytinyağlı Ahtapot", fiyat: "₺380" },
      { ad: "Karides Güveç", fiyat: "₺460" },
      { ad: "Akdeniz Salatası", fiyat: "₺160" },
      { ad: "Yerel Şarap (Kadeh)", fiyat: "₺180" },
    ],
    yorumlar: [
      { ad: "Marco T.", puan: 5, yorum: "Dining next to ancient ruins was magical." },
      { ad: "Gamze L.", puan: 4, yorum: "Fiyatlar yüksek ama atmosfer o kadar özel ki değer." },
    ],
  },

  // ---------------- GAZİANTEP ----------------
  {
    id: "gaziantep-1", il: "gaziantep", ad: "Bakırcılar Baklava Evi", kategori: "Baklava & Tatlı",
    puan: 4.9, yorumSayisi: 14300, trend: true,
    fiyat: "₺₺", adres: "Bakırcılar Çarşısı, Şahinbey / Gaziantep",
    gorsel: img(GORSEL.tatli), galeri: [img(GORSEL.tatli), img(GORSEL.osmanli), img(GORSEL.kahve)],
    ozellikler: ["Antep Fıstığı Garantili", "Günlük Taze Üretim", "Ustadan Ustaya Reçete"],
    alinti: "\"Dünyanın en iyi baklavasını yemek istiyorsanız adres burası.\"",
    neden: "Dört kuşaktır aynı ailenin elinden çıkan, tescilli Antep fıstığıyla hazırlanan baklavasıyla şehrin sembol adreslerinden.",
    menu: [
      { ad: "Fıstıklı Baklava (1 Kg)", fiyat: "₺1450" },
      { ad: "Sade Kadayıf", fiyat: "₺1100" },
      { ad: "Şöbiyet", fiyat: "₺1300" },
      { ad: "Türk Kahvesi", fiyat: "₺100" },
    ],
    yorumlar: [
      { ad: "Reyhan K.", puan: 5, yorum: "Yediğim en iyi baklava, tereddütsüz." },
      { ad: "David S.", puan: 5, yorum: "Best baklava I've ever had, worth the trip." },
    ],
  },
  {
    id: "gaziantep-2", il: "gaziantep", ad: "Kale Manzaralı Kebapçı", kategori: "Kebap & Izgara",
    puan: 4.8, yorumSayisi: 9640,
    fiyat: "₺₺₺", adres: "Gaziantep Kalesi Yakını, Şahinbey / Gaziantep",
    gorsel: img(GORSEL.et), galeri: [img(GORSEL.et), img(GORSEL.geleneksel), img(GORSEL.meze)],
    ozellikler: ["Tarihi Kale Manzarası", "Odun Ateşi", "Yöresel Baharat Karışımı"],
    alinti: "\"Ateşin kokusu, baharatların dengesi... Antep kebabının zirvesi.\"",
    neden: "Kaleye nazır terasında, kendi baharat karışımlarıyla hazırladığı kebaplarıyla şehrin en çok önerilen adreslerinden.",
    menu: [
      { ad: "Antep Kebap (Fıstıklı)", fiyat: "₺480" },
      { ad: "Beyran Çorbası", fiyat: "₺180" },
      { ad: "Katmer", fiyat: "₺220" },
      { ad: "Ayran", fiyat: "₺40" },
    ],
    yorumlar: [
      { ad: "Sedat M.", puan: 5, yorum: "Antep kebabını en iyi burada yiyeceksiniz." },
      { ad: "Nour A.", puan: 5, yorum: "Amazing flavors, the view is a bonus." },
    ],
  },
  {
    id: "gaziantep-3", il: "gaziantep", ad: "Antep Sokak Lezzetleri", kategori: "Sokak Lezzeti & Katmer",
    puan: 4.6, yorumSayisi: 5120,
    fiyat: "₺", adres: "Şahinbey, Gaziantep",
    gorsel: img(GORSEL.sokak), galeri: [img(GORSEL.sokak), img(GORSEL.tatli), img(GORSEL.pide)],
    ozellikler: ["Sabah Erken Açılış", "Odun Fırınında Katmer", "Uygun Fiyat"],
    alinti: "\"Sabah kahvaltısında sıcak katmer, Antep'te başka nerede bulunur.\"",
    neden: "Sabahın erken saatlerinde odun fırınında pişirdiği katmeriyle, yerel halkın güne başlama ritüeli haline gelmiş bir durak.",
    menu: [
      { ad: "Fıstıklı Katmer", fiyat: "₺190" },
      { ad: "Kaymaklı Katmer", fiyat: "₺170" },
      { ad: "Menengiç Kahvesi", fiyat: "₺90" },
      { ad: "Simit", fiyat: "₺25" },
    ],
    yorumlar: [
      { ad: "Fadime R.", puan: 5, yorum: "Sıcacık katmer ve menengiç kahvesi, mükemmel bir sabah." },
      { ad: "İlyas D.", puan: 4, yorum: "Sabah erken gitmek lazım, çabuk tükeniyor." },
    ],
  },
  {
    id: "gaziantep-4", il: "gaziantep", ad: "Zeugma Ev Yemekleri", kategori: "Ev Yemekleri",
    puan: 4.5, yorumSayisi: 2760,
    fiyat: "₺₺", adres: "Zeugma Mozaik Müzesi Yakını, Gaziantep",
    gorsel: img(GORSEL.geleneksel), galeri: [img(GORSEL.geleneksel), img(GORSEL.zeytinyagli), img(GORSEL.kahvalti)],
    ozellikler: ["Günlük Değişen Menü", "Ev Yapımı Tadında", "Müze Ziyareti Sonrası İdeal"],
    alinti: "\"Müze gezisinden sonra tam bir ev yemeği molası.\"",
    neden: "Zeugma Mozaik Müzesi'ni ziyaret edenlerin uğrak noktası, günlük değişen ev yemeği menüsüyle tanınıyor.",
    menu: [
      { ad: "Günün Yemeği + Pilav", fiyat: "₺220" },
      { ad: "Ali Nazik", fiyat: "₺280" },
      { ad: "Yoğurtlu Patlıcan", fiyat: "₺150" },
      { ad: "Ayran", fiyat: "₺35" },
    ],
    yorumlar: [
      { ad: "Tuğba E.", puan: 5, yorum: "Ev yemeği tadı gerçekten hissediliyor." },
      { ad: "Recep V.", puan: 4, yorum: "Sade ama doyurucu ve lezzetli." },
    ],
  },
  {
    id: "gaziantep-5", il: "gaziantep", ad: "Şirehan Kahve Durağı", kategori: "Kahve & Menengiç",
    puan: 4.7, yorumSayisi: 3320,
    fiyat: "₺", adres: "Şirehan, Gaziantep",
    gorsel: img(GORSEL.kahve), galeri: [img(GORSEL.kahve), img(GORSEL.boza), img(GORSEL.sokak)],
    ozellikler: ["Tarihi Han İçinde", "Menengiç Kahvesi", "Nargile Servisi"],
    alinti: "\"Tarihi hanın avlusunda menengiç kahvesi içmek apayrı bir keyif.\"",
    neden: "Osmanlı dönemine ait tarihi bir hanın avlusunda, yöreye özgü menengiç kahvesiyle nostaljik bir mola sunuyor.",
    menu: [
      { ad: "Menengiç Kahvesi", fiyat: "₺90" },
      { ad: "Türk Kahvesi", fiyat: "₺80" },
      { ad: "Antep Fıstıklı Kurabiye", fiyat: "₺110" },
      { ad: "Nargile", fiyat: "₺250" },
    ],
    yorumlar: [
      { ad: "Sena Y.", puan: 5, yorum: "Tarihi atmosfer ve kahve muhteşem uyum içinde." },
      { ad: "Ammar H.", puan: 4, yorum: "Sakin, keyifli bir mola noktası." },
    ],
  },
];

function mekanlariGetir(ilSlug) {
  return MEKANLAR.filter((m) => m.il === ilSlug);
}

function mekanGetir(id) {
  return MEKANLAR.find((m) => m.id === id);
}

function ilGetir(slug) {
  return ILLER.find((i) => i.slug === slug);
}
